### ISSUE TITLE
envs were created without membership of team members accounts

### ISSUE THREAD

**Issue by DaanHoogland** [shapeblue/Trillian#106]
happened to the environments created for advanced vsphere features. (FR41)

**Comment by PaulAngus** [comment]
@DaanHoogland - this should be ok now.
(hopefully fixed with https://github.com/shapeblue/Trillian/pull/101 )

**Comment by DaanHoogland** [comment]
@PaulAngus I created a test env this morning and as #101 was already merged i expected all team members to be in it. job: https://jenkins.shapeblue.com/job/acs-pr-trillian/2477/

**Comment by PaulAngus** [comment]
Fixed (now).
