### ISSUE TITLE
test_ssvm.py failed when mgmt server is ubuntu 20 on vmware environment

### ISSUE THREAD

**Issue by weizhouapache** [shapeblue/Trillian#146]
test_ssvm.py failed when mgmt server is ubuntu20 and hypervisor is vmware

http://sl-jenkins-master.sofia.shapeblue.com:8080/view/Trillian/job/Reference_Trillian/2428/
same issue
```
Intermittent failure detected: /marvin/tests/smoke/test_ssvm.py
Intermittent failure detected: /marvin/tests/smoke/test_password_server.py
Intermittent failure detected: /marvin/tests/smoke/test_deploy_vm_root_resize.py
```

the error log show

`
sshClient: DEBUG: {Cmd: ssh -i /var/cloudstack/management/.ssh/id_rsa -ostricthostkeychecking=no -oUserKnownHostsFile=/dev/null -p 3922 10.0.38.18 /usr/local/cloud/systemvm/ssvm-check.sh |grep -e ERROR -e WARNING -e FAIL via Host: 10.0.35.224} {returns: ['Warning: Identity file /var/cloudstack/management/.ssh/id_rsa not accessible: No such file or directory.', "Warning: Permanently added '[10.0.38.18]:3922' (ECDSA) to the list of known hosts.", 'root@10.0.38.18: Permission denied (publickey).']}
`

on centos7 mgmt server,  `id_rsa` is created in `/var/cloudstack/management/.ssh/` (home of `cloud` user).
in marvin utils.py, it uses `/var/cloudstack/management/.ssh/id_rsa` to connect to VR

https://github.com/apache/cloudstack/blob/97d6cd50a05e06c532ae970d3a2ab737664f8b5f/tools/marvin/marvin/lib/utils.py#L48-L50

However on ubuntu20 mgmt server, the home of `cloud` user is `/var/lib/cloudstack/management/`

**Comment by rohityadavcloud** [comment]
Has this been fixed now @weizhouapache (as this is closed)?
