### ISSUE TITLE
add Primate installation

### ISSUE THREAD

**Issue by borisstoyanov** [shapeblue/Trillian#81]
It'll be good to have primate installed when deploying an environment

**Comment by rhtyd** [comment]
By default the latest build of master from staging server can be installed until we figure out how to handle both a PR specific enviroments (PR for primate and cloudstack).
@alexandremattioli @andrijapanicsb @PaulAngus ^^

**Comment by PaulAngus** [comment]
Can you write up an explanation of what you're looking for please @rhtyd

**Comment by borisstoyanov** [comment]
One way forward could be having additional argument for primate source for example: 

if install_primate == true ;
set primate_repo = [url-given-in-jenkins-PR-or-MASTER]

and then I guess in ansible we'll need to 'yum install primate', does not need management restart so could be done at the end.

**Comment by rhtyd** [comment]
Looks like this has been handled for latest master (primate build)

**Comment by PaulAngus** [comment]
option was added to install primate
